/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type CreateUserDto = {
  /**
   * Full name of user
   *
   * @example test test
   */
  full_name: string;
  /**
   * Email address to be registered
   *
   * @example test@yopmail.com
   */
  email: string;
  /**
   * Country code of a user
   *
   * @example +91
   */
  country_code: string;
  /**
   * Phone number of a user
   *
   * @example 1234567890
   */
  phone_number: string;
  /**
   * Password (8–30 chars, must include uppercase, lowercase, number, special character)
   *
   * @example Palm@123
   */
  password: string;
  /**
   * Confirm password (must match the password field)
   *
   * @example Test@123
   */
  confirmPassword: string;
  /**
   * Selected area of interest IDs
   *
   * @example 1
   * @example 5
   * @example 9
   */
  area_of_interest: number[];
  /**
   * Login type of user. In case of social media -> use that type
   *
   * @example Local
   */
  auth_type: string;
  /**
   * Login type of user. In case of social media -> use that type
   *
   * @example App
   */
  app_type: string;
  /**
   * Device os type
   *
   * @example Android
   */
  os: string;
  /**
   * Device brand name
   *
   * @example Samsung A50
   */
  brand: string;
  /**
   * Device model number
   *
   * @example SM-A12E
   */
  model_no: string;
  /**
   * Device serial number
   *
   * @example SA4545as45a4
   */
  serial_number: string;
  /**
   * version number
   *
   * @example 1.0
   */
  version_number: string;
};

export type User = {
  user_id: number;
  full_name: string;
  email: string;
  phone_number: string;
  status: number;
  roleType: string;
  profile_image: string;
  refresh_token: string;
  access_token: string;
  country_code: string;
  fcm_token: string;
  area_of_interest_ids: string[];
  serial_number: string;
  version_number: string;
  role: string;
};

export type LoginUserDto = {
  /**
   * Email address to be registered
   *
   * @example ayushi4662@gmail.com
   */
  email: string;
  /**
   * Country code of a user
   *
   * @example +91
   */
  country_code: string;
  /**
   * Password required to be use later while login in app
   *
   * @example Palm@123
   */
  password: string;
  /**
   * Login type of user. In case of social media -> use that type
   *
   * @example Local
   */
  auth_type: string;
  /**
   * Login type of user. In case of social media -> use that type
   *
   * @example App
   */
  app_type: string;
  /**
   * Device os type
   *
   * @example Android
   */
  os: string;
  /**
   * Device brand name
   *
   * @example Samsung A50
   */
  brand: string;
  /**
   * Device model number
   *
   * @example SM-A12E
   */
  model_no: string;
  /**
   * Device serial number
   *
   * @example SA4545as45a4
   */
  serial_number: string;
  /**
   * version number
   *
   * @example 1.0
   */
  version_number: string;
};

export type ForgotPasswordDto = {
  /**
   * @example test@test.com
   */
  email: string;
};

export type ConfirmOtpDto = {
  /**
   * @example test@test.com
   */
  email: string;
  /**
   * @example 4596
   */
  otp: string;
  /**
   * @example 9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d
   */
  token: string;
};

export type ChangePasswordDto = {
  /**
   * @example Palm@2022
   */
  password: string;
  /**
   * @example Palm@2022
   */
  confirm_password: string;
  /**
   * @example test@test.com
   */
  email: string;
};

export type RefreshTokenDto = {
  /**
   * @example 123456
   */
  refreshToken: string;
};

export type SendVerifyEmailLink = {
  /**
   * @example test@test.com
   */
  email: string;
};

export type CreateImageUrlDto = {
  /**
   * Filepath which we get from Upload API
   *
   * @maxLength 400
   */
  filePath: string;
  /**
   * Generated Temp Token Number
   */
  tokenId: number;
};

export type UpdateFcmToken = {
  /**
   * fcm token of device
   *
   * @default ct4D7eG-RpaSwn2a_Mz_bf:APA91bGI9aRuTXFsfxyxyjSo07OoJzYXCl3bykbggJutqEJgx6Uq_BQ-WjHSk64kYnQvJ_r8cEkMx_JaSoXIwbEBMjBRvCSP_02eWt6fFcpvtWHhXVGsOvzO0nfTcpL1do8x_M3nARso
   */
  fcmToken: string;
};

export type ChangeNewPasswordDto = {
  old_password: string;
  new_password: string;
  confirm_password: string;
};

export type UpdateProfileDto = {
  /**
   * User's full name
   *
   * @example Test smith
   */
  full_name?: string;
  /**
   * Selected area of interest IDs (optional)
   *
   * @example 1
   * @example 5
   * @example 9
   */
  area_of_interest?: number[];
  /**
   * Profile image details (optional)
   */
  profile_image?: CreateImageUrlDto;
  /**
   * User's email address (must be a valid format)
   *
   * @example test@example.com
   */
  email?: string;
  /**
   * User's country code
   *
   * @example +91
   */
  country_code?: string;
  /**
   * User's phone number (10 digits expected)
   *
   * @example 9876543210
   */
  phone_number?: string;
};

export type RecordCourseViewDto = {
  /**
   * Course ID
   *
   * @example 1
   */
  course_id: number;
};

export type CreateUserTopicDto = {
  topic: string;
};

export type CreateInstituteDto = {
  /**
   * Name of the institute
   *
   * @example Test Institute
   */
  institute_name: string;
  /**
   * Address of the institute
   *
   * @example 123 Test St, Test City, Test Country
   */
  institute_address: string;
  /**
   * Full name of user
   *
   * @example test test
   */
  full_name: string;
  /**
   * Email address to be registered
   *
   * @example test@yopmail.com
   */
  email: string;
  /**
   * Country code of a user
   *
   * @example +91
   */
  country_code: string;
  /**
   * Phone number of a user
   *
   * @example 1234567890
   */
  phone_number: string;
  /**
   * Password (8–30 chars, must include uppercase, lowercase, number, special character)
   *
   * @example Palm@123
   */
  password: string;
  /**
   * Role of the user
   *
   * @example Institute
   */
  role: string;
  /**
   * Status of the user. 1-Active, 0-Inactive
   *
   * @example 1
   */
  status: number;
  /**
   * State id of the user
   *
   * @example 1
   */
  state_id: number;
  /**
   * City id of the user
   *
   * @example 1
   */
  city_id: number;
  /**
   * Login type of user. In case of social media -> use that type
   *
   * @example Local
   */
  auth_type: string;
  /**
   * Login type of user. In case of social media -> use that type
   *
   * @example Browser
   */
  app_type: string;
  /**
   * Device os type
   *
   * @example Windows
   */
  os: string;
  /**
   * Device brand name
   *
   * @example Samsung A50
   */
  brand: string;
  /**
   * Device model number
   *
   * @example SM-A12E
   */
  model_no: string;
  /**
   * Device serial number
   *
   * @example SA4545as45a4
   */
  serial_number: string;
  /**
   * version number
   *
   * @example 1.0
   */
  version_number: string;
  /**
   * Used to identify if the institute was created by admin or self
   *
   * @example Admin
   */
  created_by: string;
};

export type LoginInstituteDto = {
  /**
   * Email address to be registered
   *
   * @example test698@yopmail.com
   */
  email: string;
  /**
   * Role type of a user
   *
   * @example Institute
   */
  roleType: string;
  /**
   * Password required to be use later while login in app
   *
   * @example Palm@123
   */
  password: string;
  /**
   * Login type of user. In case of social media -> use that type
   *
   * @example Local
   */
  auth_type: string;
  /**
   * Login type of user. In case of social media -> use that type
   *
   * @example App
   */
  app_type: string;
  /**
   * Device os type
   *
   * @example Android
   */
  os: string;
  /**
   * Device brand name
   *
   * @example Samsung A50
   */
  brand: string;
  /**
   * Device model number
   *
   * @example SM-A12E
   */
  model_no: string;
  /**
   * Device serial number
   *
   * @example SA4545as45a4
   */
  serial_number: string;
  /**
   * version number
   *
   * @example 1.0
   */
  version_number: string;
};

export type UpdateInstituteDto = {
  /**
   * Name of the institute
   *
   * @example Test Institute
   */
  institute_name: string;
  /**
   * Address of the institute
   *
   * @example 123 Test St, Test City, Test Country
   */
  institute_address: string;
  /**
   * Authorized person name
   *
   * @example John Doe
   */
  full_name: string;
  /**
   * Email address of the institute user
   *
   * @example test@test.com
   */
  email: string;
  /**
   * Phone number of the institute user
   *
   * @example 9876543210
   */
  phone_number: string;
  /**
   * State ID of the institute location
   *
   * @example 5
   */
  state_id: number;
  /**
   * City ID of the institute location
   *
   * @example 23
   */
  city_id: number;
  /**
   * Profile image details (optional)
   */
  profile_image?: CreateImageUrlDto;
};

export type UpdateInstituteStatusDto = {
  /**
   * New status of the institute (1 = Approved, 126 = Rejected, 0 = Pending)
   *
   * @example 1
   */
  status: number;
  /**
   * New status of the institute (1 = Approved, 126 = Rejected, 0 = Pending)
   *
   * @example 1
   */
  status1: number;
  /**
   * Reason for rejection (only required when status = 126)
   *
   * @example Insufficient documents provided
   */
  reason?: string;
};

export type InstituteCourseMasterDto = {
  /**
   * Existing ID of the master type (if selecting from dropdown)
   *
   * @example 3
   */
  id?: number;
  /**
   * New name to create in master table (if not selecting existing)
   *
   * @example Diploma
   */
  name?: string;
};

export type CreateInstituteCourseDto = {
  /**
   * @example Test Course
   */
  name: string;
  /**
   * @example This is a test course
   */
  course_description: string;
  /**
   * @example 18
   */
  minimum_age?: string;
  /**
   * @example 2025-01-01
   */
  start_date: string;
  /**
   * @example 2025-12-31
   */
  end_date: string;
  /**
   * @example Admission via online form
   */
  addmision_description?: string;
  /**
   * @example Paid
   */
  fee_type: "Free" | "Paid";
  /**
   * @example 15000
   */
  fee_amount?: number;
  /**
   * @example true
   */
  installment?: number;
  /**
   * @example 1
   */
  status: number;
  /**
   * @example Online
   */
  learning_mode: "Online" | "Offline" | "Hybrid";
  /**
   * @example 1
   */
  state_id?: number;
  /**
   * @example 1
   */
  city_id?: number;
  /**
   * @example true
   */
  certification_provided: number;
  /**
   * @example 2025-11-30
   */
  last_date_of_enrollment: string;
  course_type?: InstituteCourseMasterDto;
  course_category?: InstituteCourseMasterDto;
  course_eligibility?: InstituteCourseMasterDto;
  certification_type?: InstituteCourseMasterDto;
  /**
   * URL of the institute
   *
   * @example https://example.com
   */
  institute_url?: string;
  /**
   * Profile image details (optional)
   */
  Course_image?: CreateImageUrlDto;
  /**
   * brochure pdf details (optional)
   */
  brochure?: CreateImageUrlDto;
  /**
   * syllabus pdf details (optional)
   */
  syllabus?: CreateImageUrlDto;
};

export type UpdateInstituteCourseDto = {
  /**
   * @example Updated Course Name
   */
  name?: string;
  /**
   * @example Updated description for the course
   */
  course_description?: string;
  /**
   * @example 21
   */
  minimum_age?: string;
  /**
   * @example 2025-02-01
   */
  start_date?: string;
  /**
   * @example 2025-12-31
   */
  end_date?: string;
  /**
   * @example Updated admission process details
   */
  addmision_description?: string;
  /**
   * @example Free
   */
  fee_type?: "Free" | "Paid";
  /**
   * @example 12000
   */
  fee_amount?: number;
  /**
   * @example false
   */
  installment?: number;
  /**
   * @example 1
   */
  status?: number;
  /**
   * @example Hybrid
   */
  learning_mode?: "Online" | "Offline" | "Hybrid";
  /**
   * @example 1
   */
  state_id?: number;
  /**
   * @example 1
   */
  city_id?: number;
  /**
   * @example true
   */
  certification_provided?: number;
  /**
   * @example 2025-11-30
   */
  last_date_of_enrollment?: string;
  course_type?: InstituteCourseMasterDto;
  course_category?: InstituteCourseMasterDto;
  course_eligibility?: InstituteCourseMasterDto;
  certification_type?: InstituteCourseMasterDto;
  /**
   * URL of the institute
   *
   * @example https://example.com
   */
  institute_url?: string;
  /**
   * Profile image details (optional)
   */
  Course_image?: CreateImageUrlDto;
  /**
   * brochure pdf details (optional)
   */
  brochure?: CreateImageUrlDto;
  /**
   * syllabus pdf details (optional)
   */
  syllabus?: CreateImageUrlDto;
};
