/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
import * as reactQuery from "@tanstack/react-query";
import {
  type EducationApiContext,
  useEducationApiContext,
  queryKeyFn,
} from "./educationApiContext";
import { deepMerge } from "./educationApiUtils";
import type * as Fetcher from "./educationApiFetcher";
import { educationApiFetch } from "./educationApiFetcher";
import type * as Schemas from "./educationApiSchemas";

type QueryFnOptions = {
  signal?: AbortController["signal"];
};

export type AuthControllerRegisterError = Fetcher.ErrorWrapper<undefined>;

export type AuthControllerRegisterVariables = {
  body: Schemas.CreateUserDto;
} & EducationApiContext["fetcherOptions"];

export const fetchAuthControllerRegister = (
  variables: AuthControllerRegisterVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    AuthControllerRegisterError,
    Schemas.CreateUserDto,
    {},
    {},
    {}
  >({ url: "/api/auth/v1/register", method: "post", ...variables, signal });

export const useAuthControllerRegister = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      AuthControllerRegisterError,
      AuthControllerRegisterVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useEducationApiContext();
  return reactQuery.useMutation<
    undefined,
    AuthControllerRegisterError,
    AuthControllerRegisterVariables
  >({
    mutationFn: (variables: AuthControllerRegisterVariables) =>
      fetchAuthControllerRegister(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type AuthControllerLoginUserError = Fetcher.ErrorWrapper<undefined>;

export type AuthControllerLoginUserVariables = {
  body: Schemas.LoginUserDto;
} & EducationApiContext["fetcherOptions"];

export const fetchAuthControllerLoginUser = (
  variables: AuthControllerLoginUserVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    AuthControllerLoginUserError,
    Schemas.LoginUserDto,
    {},
    {},
    {}
  >({ url: "/api/auth/v1/login", method: "post", ...variables, signal });

export const useAuthControllerLoginUser = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      AuthControllerLoginUserError,
      AuthControllerLoginUserVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useEducationApiContext();
  return reactQuery.useMutation<
    undefined,
    AuthControllerLoginUserError,
    AuthControllerLoginUserVariables
  >({
    mutationFn: (variables: AuthControllerLoginUserVariables) =>
      fetchAuthControllerLoginUser(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type AuthControllerForgotPasswordError = Fetcher.ErrorWrapper<undefined>;

export type AuthControllerForgotPasswordVariables = {
  body: Schemas.ForgotPasswordDto;
} & EducationApiContext["fetcherOptions"];

export const fetchAuthControllerForgotPassword = (
  variables: AuthControllerForgotPasswordVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    AuthControllerForgotPasswordError,
    Schemas.ForgotPasswordDto,
    {},
    {},
    {}
  >({
    url: "/api/auth/v1/forgot-password",
    method: "post",
    ...variables,
    signal,
  });

export const useAuthControllerForgotPassword = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      AuthControllerForgotPasswordError,
      AuthControllerForgotPasswordVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useEducationApiContext();
  return reactQuery.useMutation<
    undefined,
    AuthControllerForgotPasswordError,
    AuthControllerForgotPasswordVariables
  >({
    mutationFn: (variables: AuthControllerForgotPasswordVariables) =>
      fetchAuthControllerForgotPassword(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type AuthControllerSendOtpError = Fetcher.ErrorWrapper<undefined>;

export type AuthControllerSendOtpVariables = {
  body: Schemas.ForgotPasswordDto;
} & EducationApiContext["fetcherOptions"];

export const fetchAuthControllerSendOtp = (
  variables: AuthControllerSendOtpVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    AuthControllerSendOtpError,
    Schemas.ForgotPasswordDto,
    {},
    {},
    {}
  >({ url: "/api/auth/v1/send-otp", method: "post", ...variables, signal });

export const useAuthControllerSendOtp = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      AuthControllerSendOtpError,
      AuthControllerSendOtpVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useEducationApiContext();
  return reactQuery.useMutation<
    undefined,
    AuthControllerSendOtpError,
    AuthControllerSendOtpVariables
  >({
    mutationFn: (variables: AuthControllerSendOtpVariables) =>
      fetchAuthControllerSendOtp(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type AuthControllerConfirmOtpError = Fetcher.ErrorWrapper<undefined>;

export type AuthControllerConfirmOtpVariables = {
  body: Schemas.ConfirmOtpDto;
} & EducationApiContext["fetcherOptions"];

export const fetchAuthControllerConfirmOtp = (
  variables: AuthControllerConfirmOtpVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    AuthControllerConfirmOtpError,
    Schemas.ConfirmOtpDto,
    {},
    {},
    {}
  >({ url: "/api/auth/v1/confirm-otp", method: "post", ...variables, signal });

export const useAuthControllerConfirmOtp = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      AuthControllerConfirmOtpError,
      AuthControllerConfirmOtpVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useEducationApiContext();
  return reactQuery.useMutation<
    undefined,
    AuthControllerConfirmOtpError,
    AuthControllerConfirmOtpVariables
  >({
    mutationFn: (variables: AuthControllerConfirmOtpVariables) =>
      fetchAuthControllerConfirmOtp(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type AuthControllerVerifyOtpError = Fetcher.ErrorWrapper<undefined>;

export type AuthControllerVerifyOtpVariables = {
  body: Schemas.ConfirmOtpDto;
} & EducationApiContext["fetcherOptions"];

export const fetchAuthControllerVerifyOtp = (
  variables: AuthControllerVerifyOtpVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    AuthControllerVerifyOtpError,
    Schemas.ConfirmOtpDto,
    {},
    {},
    {}
  >({ url: "/api/auth/v1/verify-otp", method: "post", ...variables, signal });

export const useAuthControllerVerifyOtp = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      AuthControllerVerifyOtpError,
      AuthControllerVerifyOtpVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useEducationApiContext();
  return reactQuery.useMutation<
    undefined,
    AuthControllerVerifyOtpError,
    AuthControllerVerifyOtpVariables
  >({
    mutationFn: (variables: AuthControllerVerifyOtpVariables) =>
      fetchAuthControllerVerifyOtp(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type AuthControllerResetPasswordError = Fetcher.ErrorWrapper<undefined>;

export type AuthControllerResetPasswordVariables = {
  body: Schemas.ChangePasswordDto;
} & EducationApiContext["fetcherOptions"];

export const fetchAuthControllerResetPassword = (
  variables: AuthControllerResetPasswordVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    AuthControllerResetPasswordError,
    Schemas.ChangePasswordDto,
    {},
    {},
    {}
  >({
    url: "/api/auth/v1/reset-password",
    method: "post",
    ...variables,
    signal,
  });

export const useAuthControllerResetPassword = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      AuthControllerResetPasswordError,
      AuthControllerResetPasswordVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useEducationApiContext();
  return reactQuery.useMutation<
    undefined,
    AuthControllerResetPasswordError,
    AuthControllerResetPasswordVariables
  >({
    mutationFn: (variables: AuthControllerResetPasswordVariables) =>
      fetchAuthControllerResetPassword(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type AuthControllerResetPasswordAliasError =
  Fetcher.ErrorWrapper<undefined>;

export type AuthControllerResetPasswordAliasVariables = {
  body: Schemas.ChangePasswordDto;
} & EducationApiContext["fetcherOptions"];

export const fetchAuthControllerResetPasswordAlias = (
  variables: AuthControllerResetPasswordAliasVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    AuthControllerResetPasswordAliasError,
    Schemas.ChangePasswordDto,
    {},
    {},
    {}
  >({
    url: "/api/auth/v1/resetpassword",
    method: "post",
    ...variables,
    signal,
  });

export const useAuthControllerResetPasswordAlias = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      AuthControllerResetPasswordAliasError,
      AuthControllerResetPasswordAliasVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useEducationApiContext();
  return reactQuery.useMutation<
    undefined,
    AuthControllerResetPasswordAliasError,
    AuthControllerResetPasswordAliasVariables
  >({
    mutationFn: (variables: AuthControllerResetPasswordAliasVariables) =>
      fetchAuthControllerResetPasswordAlias(
        deepMerge(fetcherOptions, variables),
      ),
    ...options,
  });
};

export type AuthControllerRefreshTokenError = Fetcher.ErrorWrapper<undefined>;

export type AuthControllerRefreshTokenVariables = {
  body: Schemas.RefreshTokenDto;
} & EducationApiContext["fetcherOptions"];

export const fetchAuthControllerRefreshToken = (
  variables: AuthControllerRefreshTokenVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    AuthControllerRefreshTokenError,
    Schemas.RefreshTokenDto,
    {},
    {},
    {}
  >({
    url: "/api/auth/v1/refresh-token",
    method: "post",
    ...variables,
    signal,
  });

export const useAuthControllerRefreshToken = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      AuthControllerRefreshTokenError,
      AuthControllerRefreshTokenVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useEducationApiContext();
  return reactQuery.useMutation<
    undefined,
    AuthControllerRefreshTokenError,
    AuthControllerRefreshTokenVariables
  >({
    mutationFn: (variables: AuthControllerRefreshTokenVariables) =>
      fetchAuthControllerRefreshToken(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type UploadControllerUploadFileQueryParams = {
  type?: "profile" | "files";
};

export type UploadControllerUploadFileError = Fetcher.ErrorWrapper<undefined>;

export type UploadControllerUploadFileRequestBody = {
  /**
   * @format binary
   */
  file?: Blob;
};

export type UploadControllerUploadFileVariables = {
  body?: UploadControllerUploadFileRequestBody;
  queryParams?: UploadControllerUploadFileQueryParams;
} & EducationApiContext["fetcherOptions"];

export const fetchUploadControllerUploadFile = (
  variables: UploadControllerUploadFileVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    UploadControllerUploadFileError,
    UploadControllerUploadFileRequestBody,
    {},
    UploadControllerUploadFileQueryParams,
    {}
  >({ url: "/api/upload/v1/file", method: "post", ...variables, signal });

export const useUploadControllerUploadFile = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      UploadControllerUploadFileError,
      UploadControllerUploadFileVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useEducationApiContext();
  return reactQuery.useMutation<
    undefined,
    UploadControllerUploadFileError,
    UploadControllerUploadFileVariables
  >({
    mutationFn: (variables: UploadControllerUploadFileVariables) =>
      fetchUploadControllerUploadFile(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type UploadControllerUploadFilesQueryParams = {
  type?: "profile" | "files";
};

export type UploadControllerUploadFilesError = Fetcher.ErrorWrapper<undefined>;

export type UploadControllerUploadFilesRequestBody = {
  files?: Blob[];
};

export type UploadControllerUploadFilesVariables = {
  body?: UploadControllerUploadFilesRequestBody;
  queryParams?: UploadControllerUploadFilesQueryParams;
} & EducationApiContext["fetcherOptions"];

export const fetchUploadControllerUploadFiles = (
  variables: UploadControllerUploadFilesVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    UploadControllerUploadFilesError,
    UploadControllerUploadFilesRequestBody,
    {},
    UploadControllerUploadFilesQueryParams,
    {}
  >({ url: "/api/upload/v1/files", method: "post", ...variables, signal });

export const useUploadControllerUploadFiles = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      UploadControllerUploadFilesError,
      UploadControllerUploadFilesVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useEducationApiContext();
  return reactQuery.useMutation<
    undefined,
    UploadControllerUploadFilesError,
    UploadControllerUploadFilesVariables
  >({
    mutationFn: (variables: UploadControllerUploadFilesVariables) =>
      fetchUploadControllerUploadFiles(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type AiControllerGetNearbyGroundsPathParams = {
  /**
   * The ID of the user
   */
  userId: number;
};

export type AiControllerGetNearbyGroundsQueryParams = {
  /**
   * Free-text search query (e.g. 'find cricket ground near me'). If omitted, searches based on user profile sports/city.
   */
  query?: string;
};

export type AiControllerGetNearbyGroundsError = Fetcher.ErrorWrapper<undefined>;

export type AiControllerGetNearbyGroundsVariables = {
  pathParams: AiControllerGetNearbyGroundsPathParams;
  queryParams?: AiControllerGetNearbyGroundsQueryParams;
} & EducationApiContext["fetcherOptions"];

export const fetchAiControllerGetNearbyGrounds = (
  variables: AiControllerGetNearbyGroundsVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    AiControllerGetNearbyGroundsError,
    undefined,
    {},
    AiControllerGetNearbyGroundsQueryParams,
    AiControllerGetNearbyGroundsPathParams
  >({
    url: "/api/ai/nearby-grounds/{userId}",
    method: "get",
    ...variables,
    signal,
  });

export function aiControllerGetNearbyGroundsQuery(
  variables: AiControllerGetNearbyGroundsVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<undefined>;
};

export function aiControllerGetNearbyGroundsQuery(
  variables: AiControllerGetNearbyGroundsVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<undefined>)
    | reactQuery.SkipToken;
};

export function aiControllerGetNearbyGroundsQuery(
  variables: AiControllerGetNearbyGroundsVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/api/ai/nearby-grounds/{userId}",
      operationId: "aiControllerGetNearbyGrounds",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchAiControllerGetNearbyGrounds(variables, signal),
  };
}

export const useSuspenseAiControllerGetNearbyGrounds = <TData = undefined,>(
  variables: AiControllerGetNearbyGroundsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      undefined,
      AiControllerGetNearbyGroundsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useEducationApiContext(options);
  return reactQuery.useSuspenseQuery<
    undefined,
    AiControllerGetNearbyGroundsError,
    TData
  >({
    ...aiControllerGetNearbyGroundsQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useAiControllerGetNearbyGrounds = <TData = undefined,>(
  variables: AiControllerGetNearbyGroundsVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      undefined,
      AiControllerGetNearbyGroundsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useEducationApiContext(options);
  return reactQuery.useQuery<
    undefined,
    AiControllerGetNearbyGroundsError,
    TData
  >({
    ...aiControllerGetNearbyGroundsQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type AiControllerGetPlayerStatsPathParams = {
  /**
   * The ID of the user
   */
  userId: number;
};

export type AiControllerGetPlayerStatsError = Fetcher.ErrorWrapper<undefined>;

export type AiControllerGetPlayerStatsVariables = {
  pathParams: AiControllerGetPlayerStatsPathParams;
} & EducationApiContext["fetcherOptions"];

export const fetchAiControllerGetPlayerStats = (
  variables: AiControllerGetPlayerStatsVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    AiControllerGetPlayerStatsError,
    undefined,
    {},
    {},
    AiControllerGetPlayerStatsPathParams
  >({
    url: "/api/ai/player-stats/{userId}",
    method: "get",
    ...variables,
    signal,
  });

export function aiControllerGetPlayerStatsQuery(
  variables: AiControllerGetPlayerStatsVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<undefined>;
};

export function aiControllerGetPlayerStatsQuery(
  variables: AiControllerGetPlayerStatsVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<undefined>)
    | reactQuery.SkipToken;
};

export function aiControllerGetPlayerStatsQuery(
  variables: AiControllerGetPlayerStatsVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/api/ai/player-stats/{userId}",
      operationId: "aiControllerGetPlayerStats",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchAiControllerGetPlayerStats(variables, signal),
  };
}

export const useSuspenseAiControllerGetPlayerStats = <TData = undefined,>(
  variables: AiControllerGetPlayerStatsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      undefined,
      AiControllerGetPlayerStatsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useEducationApiContext(options);
  return reactQuery.useSuspenseQuery<
    undefined,
    AiControllerGetPlayerStatsError,
    TData
  >({
    ...aiControllerGetPlayerStatsQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useAiControllerGetPlayerStats = <TData = undefined,>(
  variables: AiControllerGetPlayerStatsVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      undefined,
      AiControllerGetPlayerStatsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useEducationApiContext(options);
  return reactQuery.useQuery<undefined, AiControllerGetPlayerStatsError, TData>(
    {
      ...aiControllerGetPlayerStatsQuery(
        variables === reactQuery.skipToken
          ? variables
          : deepMerge(fetcherOptions, variables),
      ),
      ...options,
      ...queryOptions,
    },
  );
};

export type GroundControllerCreateGroundError = Fetcher.ErrorWrapper<undefined>;

export type GroundControllerCreateGroundVariables = {
  body: Schemas.CreateGroundDto;
} & EducationApiContext["fetcherOptions"];

export const fetchGroundControllerCreateGround = (
  variables: GroundControllerCreateGroundVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    GroundControllerCreateGroundError,
    Schemas.CreateGroundDto,
    {},
    {},
    {}
  >({ url: "/api/grounds/v1", method: "post", ...variables, signal });

export const useGroundControllerCreateGround = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      GroundControllerCreateGroundError,
      GroundControllerCreateGroundVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useEducationApiContext();
  return reactQuery.useMutation<
    undefined,
    GroundControllerCreateGroundError,
    GroundControllerCreateGroundVariables
  >({
    mutationFn: (variables: GroundControllerCreateGroundVariables) =>
      fetchGroundControllerCreateGround(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type GroundControllerGetPublicGroundsQueryParams = {
  /**
   * Page number
   *
   * @default 1
   */
  page?: number;
  /**
   * Records per page
   *
   * @default 10
   */
  limit?: number;
  /**
   * Search by ground name or city
   */
  search?: string;
  /**
   * Filter by city
   */
  city?: string;
  /**
   * Filter by sport ID
   */
  sportId?: number;
  /**
   * Minimum slot price filter
   */
  priceFrom?: number;
  /**
   * Maximum slot price filter
   */
  priceTo?: number;
  /**
   * User latitude for geo-radius search
   */
  latitude?: number;
  /**
   * User longitude for geo-radius search
   */
  longitude?: number;
  /**
   * Search radius in km (requires latitude & longitude). Default: 5 km
   *
   * @default 5
   */
  radius?: number;
  /**
   * Sort field
   *
   * @default created_at
   */
  sortBy?: string;
  /**
   * Sort order
   *
   * @default DESC
   */
  sortOrder?: "ASC" | "DESC";
};

export type GroundControllerGetPublicGroundsError =
  Fetcher.ErrorWrapper<undefined>;

export type GroundControllerGetPublicGroundsVariables = {
  queryParams?: GroundControllerGetPublicGroundsQueryParams;
} & EducationApiContext["fetcherOptions"];

export const fetchGroundControllerGetPublicGrounds = (
  variables: GroundControllerGetPublicGroundsVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    GroundControllerGetPublicGroundsError,
    undefined,
    {},
    GroundControllerGetPublicGroundsQueryParams,
    {}
  >({ url: "/api/grounds/v1", method: "get", ...variables, signal });

export function groundControllerGetPublicGroundsQuery(
  variables: GroundControllerGetPublicGroundsVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<undefined>;
};

export function groundControllerGetPublicGroundsQuery(
  variables: GroundControllerGetPublicGroundsVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<undefined>)
    | reactQuery.SkipToken;
};

export function groundControllerGetPublicGroundsQuery(
  variables: GroundControllerGetPublicGroundsVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/api/grounds/v1",
      operationId: "groundControllerGetPublicGrounds",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchGroundControllerGetPublicGrounds(variables, signal),
  };
}

export const useSuspenseGroundControllerGetPublicGrounds = <TData = undefined,>(
  variables: GroundControllerGetPublicGroundsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      undefined,
      GroundControllerGetPublicGroundsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useEducationApiContext(options);
  return reactQuery.useSuspenseQuery<
    undefined,
    GroundControllerGetPublicGroundsError,
    TData
  >({
    ...groundControllerGetPublicGroundsQuery(
      deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export const useGroundControllerGetPublicGrounds = <TData = undefined,>(
  variables: GroundControllerGetPublicGroundsVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      undefined,
      GroundControllerGetPublicGroundsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useEducationApiContext(options);
  return reactQuery.useQuery<
    undefined,
    GroundControllerGetPublicGroundsError,
    TData
  >({
    ...groundControllerGetPublicGroundsQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type GroundControllerGetMyGroundsQueryParams = {
  /**
   * Page number
   *
   * @default 1
   */
  page?: number;
  /**
   * Records per page
   *
   * @default 10
   */
  limit?: number;
  /**
   * Search by name or city
   */
  search?: string;
  /**
   * Filter by status: 1=active, 0=inactive
   */
  status?: number;
  /**
   * Filter by sport ID
   */
  sportId?: number;
  /**
   * Sort field
   *
   * @default created_at
   */
  sortBy?: string;
  /**
   * Sort order
   *
   * @default DESC
   */
  sortOrder?: "ASC" | "DESC";
};

export type GroundControllerGetMyGroundsError = Fetcher.ErrorWrapper<undefined>;

export type GroundControllerGetMyGroundsVariables = {
  queryParams?: GroundControllerGetMyGroundsQueryParams;
} & EducationApiContext["fetcherOptions"];

export const fetchGroundControllerGetMyGrounds = (
  variables: GroundControllerGetMyGroundsVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    GroundControllerGetMyGroundsError,
    undefined,
    {},
    GroundControllerGetMyGroundsQueryParams,
    {}
  >({ url: "/api/grounds/v1/my", method: "get", ...variables, signal });

export function groundControllerGetMyGroundsQuery(
  variables: GroundControllerGetMyGroundsVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<undefined>;
};

export function groundControllerGetMyGroundsQuery(
  variables: GroundControllerGetMyGroundsVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<undefined>)
    | reactQuery.SkipToken;
};

export function groundControllerGetMyGroundsQuery(
  variables: GroundControllerGetMyGroundsVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/api/grounds/v1/my",
      operationId: "groundControllerGetMyGrounds",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchGroundControllerGetMyGrounds(variables, signal),
  };
}

export const useSuspenseGroundControllerGetMyGrounds = <TData = undefined,>(
  variables: GroundControllerGetMyGroundsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      undefined,
      GroundControllerGetMyGroundsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useEducationApiContext(options);
  return reactQuery.useSuspenseQuery<
    undefined,
    GroundControllerGetMyGroundsError,
    TData
  >({
    ...groundControllerGetMyGroundsQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useGroundControllerGetMyGrounds = <TData = undefined,>(
  variables: GroundControllerGetMyGroundsVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      undefined,
      GroundControllerGetMyGroundsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useEducationApiContext(options);
  return reactQuery.useQuery<
    undefined,
    GroundControllerGetMyGroundsError,
    TData
  >({
    ...groundControllerGetMyGroundsQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type GroundControllerGetGroundDetailsPathParams = {
  id: number;
};

export type GroundControllerGetGroundDetailsError =
  Fetcher.ErrorWrapper<undefined>;

export type GroundControllerGetGroundDetailsVariables = {
  pathParams: GroundControllerGetGroundDetailsPathParams;
} & EducationApiContext["fetcherOptions"];

export const fetchGroundControllerGetGroundDetails = (
  variables: GroundControllerGetGroundDetailsVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    GroundControllerGetGroundDetailsError,
    undefined,
    {},
    {},
    GroundControllerGetGroundDetailsPathParams
  >({ url: "/api/grounds/v1/{id}", method: "get", ...variables, signal });

export function groundControllerGetGroundDetailsQuery(
  variables: GroundControllerGetGroundDetailsVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<undefined>;
};

export function groundControllerGetGroundDetailsQuery(
  variables: GroundControllerGetGroundDetailsVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<undefined>)
    | reactQuery.SkipToken;
};

export function groundControllerGetGroundDetailsQuery(
  variables: GroundControllerGetGroundDetailsVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/api/grounds/v1/{id}",
      operationId: "groundControllerGetGroundDetails",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchGroundControllerGetGroundDetails(variables, signal),
  };
}

export const useSuspenseGroundControllerGetGroundDetails = <TData = undefined,>(
  variables: GroundControllerGetGroundDetailsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      undefined,
      GroundControllerGetGroundDetailsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useEducationApiContext(options);
  return reactQuery.useSuspenseQuery<
    undefined,
    GroundControllerGetGroundDetailsError,
    TData
  >({
    ...groundControllerGetGroundDetailsQuery(
      deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export const useGroundControllerGetGroundDetails = <TData = undefined,>(
  variables: GroundControllerGetGroundDetailsVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      undefined,
      GroundControllerGetGroundDetailsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useEducationApiContext(options);
  return reactQuery.useQuery<
    undefined,
    GroundControllerGetGroundDetailsError,
    TData
  >({
    ...groundControllerGetGroundDetailsQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type GroundControllerUpdateGroundPathParams = {
  id: number;
};

export type GroundControllerUpdateGroundError = Fetcher.ErrorWrapper<undefined>;

export type GroundControllerUpdateGroundVariables = {
  body?: Schemas.UpdateGroundDto;
  pathParams: GroundControllerUpdateGroundPathParams;
} & EducationApiContext["fetcherOptions"];

export const fetchGroundControllerUpdateGround = (
  variables: GroundControllerUpdateGroundVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    GroundControllerUpdateGroundError,
    Schemas.UpdateGroundDto,
    {},
    {},
    GroundControllerUpdateGroundPathParams
  >({ url: "/api/grounds/v1/{id}", method: "put", ...variables, signal });

export const useGroundControllerUpdateGround = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      GroundControllerUpdateGroundError,
      GroundControllerUpdateGroundVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useEducationApiContext();
  return reactQuery.useMutation<
    undefined,
    GroundControllerUpdateGroundError,
    GroundControllerUpdateGroundVariables
  >({
    mutationFn: (variables: GroundControllerUpdateGroundVariables) =>
      fetchGroundControllerUpdateGround(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type GroundControllerDeleteGroundPathParams = {
  id: number;
};

export type GroundControllerDeleteGroundError = Fetcher.ErrorWrapper<undefined>;

export type GroundControllerDeleteGroundVariables = {
  pathParams: GroundControllerDeleteGroundPathParams;
} & EducationApiContext["fetcherOptions"];

export const fetchGroundControllerDeleteGround = (
  variables: GroundControllerDeleteGroundVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    GroundControllerDeleteGroundError,
    undefined,
    {},
    {},
    GroundControllerDeleteGroundPathParams
  >({ url: "/api/grounds/v1/{id}", method: "delete", ...variables, signal });

export const useGroundControllerDeleteGround = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      GroundControllerDeleteGroundError,
      GroundControllerDeleteGroundVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useEducationApiContext();
  return reactQuery.useMutation<
    undefined,
    GroundControllerDeleteGroundError,
    GroundControllerDeleteGroundVariables
  >({
    mutationFn: (variables: GroundControllerDeleteGroundVariables) =>
      fetchGroundControllerDeleteGround(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type GroundControllerGetAvailabilityPathParams = {
  id: number;
};

export type GroundControllerGetAvailabilityQueryParams = {
  /**
   * Date to check availability (YYYY-MM-DD)
   */
  date: string;
  /**
   * Filter by sport ID to verify the ground supports this sport
   */
  sportId?: number;
};

export type GroundControllerGetAvailabilityError =
  Fetcher.ErrorWrapper<undefined>;

export type GroundControllerGetAvailabilityVariables = {
  pathParams: GroundControllerGetAvailabilityPathParams;
  queryParams: GroundControllerGetAvailabilityQueryParams;
} & EducationApiContext["fetcherOptions"];

export const fetchGroundControllerGetAvailability = (
  variables: GroundControllerGetAvailabilityVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    GroundControllerGetAvailabilityError,
    undefined,
    {},
    GroundControllerGetAvailabilityQueryParams,
    GroundControllerGetAvailabilityPathParams
  >({
    url: "/api/grounds/v1/{id}/availability",
    method: "get",
    ...variables,
    signal,
  });

export function groundControllerGetAvailabilityQuery(
  variables: GroundControllerGetAvailabilityVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<undefined>;
};

export function groundControllerGetAvailabilityQuery(
  variables: GroundControllerGetAvailabilityVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<undefined>)
    | reactQuery.SkipToken;
};

export function groundControllerGetAvailabilityQuery(
  variables: GroundControllerGetAvailabilityVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/api/grounds/v1/{id}/availability",
      operationId: "groundControllerGetAvailability",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchGroundControllerGetAvailability(variables, signal),
  };
}

export const useSuspenseGroundControllerGetAvailability = <TData = undefined,>(
  variables: GroundControllerGetAvailabilityVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      undefined,
      GroundControllerGetAvailabilityError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useEducationApiContext(options);
  return reactQuery.useSuspenseQuery<
    undefined,
    GroundControllerGetAvailabilityError,
    TData
  >({
    ...groundControllerGetAvailabilityQuery(
      deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export const useGroundControllerGetAvailability = <TData = undefined,>(
  variables: GroundControllerGetAvailabilityVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      undefined,
      GroundControllerGetAvailabilityError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useEducationApiContext(options);
  return reactQuery.useQuery<
    undefined,
    GroundControllerGetAvailabilityError,
    TData
  >({
    ...groundControllerGetAvailabilityQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type GroundControllerAddImagePathParams = {
  id: number;
};

export type GroundControllerAddImageError = Fetcher.ErrorWrapper<undefined>;

export type GroundControllerAddImageVariables = {
  body: Schemas.GroundImageDto;
  pathParams: GroundControllerAddImagePathParams;
} & EducationApiContext["fetcherOptions"];

export const fetchGroundControllerAddImage = (
  variables: GroundControllerAddImageVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    GroundControllerAddImageError,
    Schemas.GroundImageDto,
    {},
    {},
    GroundControllerAddImagePathParams
  >({
    url: "/api/grounds/v1/{id}/images",
    method: "post",
    ...variables,
    signal,
  });

export const useGroundControllerAddImage = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      GroundControllerAddImageError,
      GroundControllerAddImageVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useEducationApiContext();
  return reactQuery.useMutation<
    undefined,
    GroundControllerAddImageError,
    GroundControllerAddImageVariables
  >({
    mutationFn: (variables: GroundControllerAddImageVariables) =>
      fetchGroundControllerAddImage(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type GroundControllerRemoveImagePathParams = {
  id: number;
  imageId: number;
};

export type GroundControllerRemoveImageError = Fetcher.ErrorWrapper<undefined>;

export type GroundControllerRemoveImageVariables = {
  pathParams: GroundControllerRemoveImagePathParams;
} & EducationApiContext["fetcherOptions"];

export const fetchGroundControllerRemoveImage = (
  variables: GroundControllerRemoveImageVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    GroundControllerRemoveImageError,
    undefined,
    {},
    {},
    GroundControllerRemoveImagePathParams
  >({
    url: "/api/grounds/v1/{id}/images/{imageId}",
    method: "delete",
    ...variables,
    signal,
  });

export const useGroundControllerRemoveImage = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      GroundControllerRemoveImageError,
      GroundControllerRemoveImageVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useEducationApiContext();
  return reactQuery.useMutation<
    undefined,
    GroundControllerRemoveImageError,
    GroundControllerRemoveImageVariables
  >({
    mutationFn: (variables: GroundControllerRemoveImageVariables) =>
      fetchGroundControllerRemoveImage(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type GroundControllerAddSlotPathParams = {
  id: number;
};

export type GroundControllerAddSlotError = Fetcher.ErrorWrapper<undefined>;

export type GroundControllerAddSlotRequestBody = Schemas.GroundSlotDto[];

export type GroundControllerAddSlotVariables = {
  body?: GroundControllerAddSlotRequestBody;
  pathParams: GroundControllerAddSlotPathParams;
} & EducationApiContext["fetcherOptions"];

export const fetchGroundControllerAddSlot = (
  variables: GroundControllerAddSlotVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    GroundControllerAddSlotError,
    GroundControllerAddSlotRequestBody,
    {},
    {},
    GroundControllerAddSlotPathParams
  >({
    url: "/api/grounds/v1/{id}/slots",
    method: "post",
    ...variables,
    signal,
  });

export const useGroundControllerAddSlot = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      GroundControllerAddSlotError,
      GroundControllerAddSlotVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useEducationApiContext();
  return reactQuery.useMutation<
    undefined,
    GroundControllerAddSlotError,
    GroundControllerAddSlotVariables
  >({
    mutationFn: (variables: GroundControllerAddSlotVariables) =>
      fetchGroundControllerAddSlot(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type GroundControllerUpdateSlotPathParams = {
  id: number;
  slotId: number;
};

export type GroundControllerUpdateSlotError = Fetcher.ErrorWrapper<undefined>;

export type GroundControllerUpdateSlotVariables = {
  body?: Schemas.UpdateGroundSlotDto;
  pathParams: GroundControllerUpdateSlotPathParams;
} & EducationApiContext["fetcherOptions"];

export const fetchGroundControllerUpdateSlot = (
  variables: GroundControllerUpdateSlotVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    GroundControllerUpdateSlotError,
    Schemas.UpdateGroundSlotDto,
    {},
    {},
    GroundControllerUpdateSlotPathParams
  >({
    url: "/api/grounds/v1/{id}/slots/{slotId}",
    method: "put",
    ...variables,
    signal,
  });

export const useGroundControllerUpdateSlot = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      GroundControllerUpdateSlotError,
      GroundControllerUpdateSlotVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useEducationApiContext();
  return reactQuery.useMutation<
    undefined,
    GroundControllerUpdateSlotError,
    GroundControllerUpdateSlotVariables
  >({
    mutationFn: (variables: GroundControllerUpdateSlotVariables) =>
      fetchGroundControllerUpdateSlot(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type GroundControllerDeleteSlotPathParams = {
  id: number;
  slotId: number;
};

export type GroundControllerDeleteSlotError = Fetcher.ErrorWrapper<undefined>;

export type GroundControllerDeleteSlotVariables = {
  pathParams: GroundControllerDeleteSlotPathParams;
} & EducationApiContext["fetcherOptions"];

export const fetchGroundControllerDeleteSlot = (
  variables: GroundControllerDeleteSlotVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    GroundControllerDeleteSlotError,
    undefined,
    {},
    {},
    GroundControllerDeleteSlotPathParams
  >({
    url: "/api/grounds/v1/{id}/slots/{slotId}",
    method: "delete",
    ...variables,
    signal,
  });

export const useGroundControllerDeleteSlot = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      GroundControllerDeleteSlotError,
      GroundControllerDeleteSlotVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useEducationApiContext();
  return reactQuery.useMutation<
    undefined,
    GroundControllerDeleteSlotError,
    GroundControllerDeleteSlotVariables
  >({
    mutationFn: (variables: GroundControllerDeleteSlotVariables) =>
      fetchGroundControllerDeleteSlot(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type MasterControllerGetSportsError = Fetcher.ErrorWrapper<undefined>;

export type MasterControllerGetSportsVariables =
  EducationApiContext["fetcherOptions"];

export const fetchMasterControllerGetSports = (
  variables: MasterControllerGetSportsVariables,
  signal?: AbortSignal,
) =>
  educationApiFetch<
    undefined,
    MasterControllerGetSportsError,
    undefined,
    {},
    {},
    {}
  >({ url: "/api/master/v1/sports", method: "get", ...variables, signal });

export function masterControllerGetSportsQuery(
  variables: MasterControllerGetSportsVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<undefined>;
};

export function masterControllerGetSportsQuery(
  variables: MasterControllerGetSportsVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<undefined>)
    | reactQuery.SkipToken;
};

export function masterControllerGetSportsQuery(
  variables: MasterControllerGetSportsVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/api/master/v1/sports",
      operationId: "masterControllerGetSports",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchMasterControllerGetSports(variables, signal),
  };
}

export const useSuspenseMasterControllerGetSports = <TData = undefined,>(
  variables: MasterControllerGetSportsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      undefined,
      MasterControllerGetSportsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useEducationApiContext(options);
  return reactQuery.useSuspenseQuery<
    undefined,
    MasterControllerGetSportsError,
    TData
  >({
    ...masterControllerGetSportsQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useMasterControllerGetSports = <TData = undefined,>(
  variables: MasterControllerGetSportsVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      undefined,
      MasterControllerGetSportsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useEducationApiContext(options);
  return reactQuery.useQuery<undefined, MasterControllerGetSportsError, TData>({
    ...masterControllerGetSportsQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type QueryOperation =
  | {
      path: "/api/ai/nearby-grounds/{userId}";
      operationId: "aiControllerGetNearbyGrounds";
      variables: AiControllerGetNearbyGroundsVariables | reactQuery.SkipToken;
    }
  | {
      path: "/api/ai/player-stats/{userId}";
      operationId: "aiControllerGetPlayerStats";
      variables: AiControllerGetPlayerStatsVariables | reactQuery.SkipToken;
    }
  | {
      path: "/api/grounds/v1";
      operationId: "groundControllerGetPublicGrounds";
      variables:
        | GroundControllerGetPublicGroundsVariables
        | reactQuery.SkipToken;
    }
  | {
      path: "/api/grounds/v1/my";
      operationId: "groundControllerGetMyGrounds";
      variables: GroundControllerGetMyGroundsVariables | reactQuery.SkipToken;
    }
  | {
      path: "/api/grounds/v1/{id}";
      operationId: "groundControllerGetGroundDetails";
      variables:
        | GroundControllerGetGroundDetailsVariables
        | reactQuery.SkipToken;
    }
  | {
      path: "/api/grounds/v1/{id}/availability";
      operationId: "groundControllerGetAvailability";
      variables:
        | GroundControllerGetAvailabilityVariables
        | reactQuery.SkipToken;
    }
  | {
      path: "/api/master/v1/sports";
      operationId: "masterControllerGetSports";
      variables: MasterControllerGetSportsVariables | reactQuery.SkipToken;
    };
