/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type ProfileImageDto = {
  /**
   * Uploaded filename
   *
   * @example 1785412662411.png
   */
  filename: string;
  /**
   * URL of the uploaded image
   *
   * @example /drive/files/1785412662411.png
   */
  url: string;
};

export type CreateUserDto = {
  /**
   * Display name of user
   *
   * @example Rajesh Kumar
   */
  display_name: string;
  /**
   * Country code of a user
   *
   * @example +91
   */
  country_code: string;
  /**
   * Phone number of a user
   *
   * @example 9876543210
   */
  mobile_number: string;
  /**
   * Role of the user
   *
   * @example PLAYER
   * @default PLAYER
   */
  role: "PLAYER" | "GROUND_OWNER" | "ORGANIZER" | "ADMIN";
  /**
   * Profile image upload object (filename and url), can also accept a plain URL string
   */
  profile_image?: ProfileImageDto;
  /**
   * Auth type of user. Local/Social media type
   *
   * @example Local
   */
  auth_type: string;
  /**
   * App type. App or Browser
   *
   * @example App
   */
  app_type: string;
  /**
   * Device os type
   *
   * @example Android
   */
  os: string;
  /**
   * Device brand name
   *
   * @example Samsung A50
   */
  brand: string;
  /**
   * Device model number
   *
   * @example SM-A12E
   */
  model_no: string;
  /**
   * Device serial number
   *
   * @example SA4545as45a4
   */
  serial_number: string;
  /**
   * version number
   *
   * @example 1.0
   */
  version_number: string;
  /**
   * FCM token of the device
   *
   * @example fcm_token_001
   */
  fcm_token?: string;
  /**
   * List of sport IDs that the user plays or is interested in
   *
   * @example 1
   * @example 2
   */
  sports?: string[];
};

export type LoginUserDto = {
  /**
   * Phone number of a user
   *
   * @example 9876543210
   */
  mobile_number: string;
  /**
   * Country code of a user
   *
   * @example +91
   */
  country_code: string;
  /**
   * Login type of user.
   *
   * @example App
   */
  app_type: string;
  /**
   * Device os type
   *
   * @example Android
   */
  os: string;
  /**
   * Device brand name
   *
   * @example Samsung A50
   */
  brand: string;
  /**
   * Device model number
   *
   * @example SM-A12E
   */
  model_no: string;
  /**
   * Device serial number
   *
   * @example SA4545as45a4
   */
  serial_number: string;
  /**
   * version number
   *
   * @example 1.0
   */
  version_number: string;
  /**
   * FCM token of the device
   *
   * @example fcm_token_001
   */
  fcm_token?: string;
};

export type ForgotPasswordDto = {
  /**
   * Phone number of a user
   *
   * @example 9876543210
   */
  mobile_number: string;
  /**
   * Country code of a user
   *
   * @example +91
   */
  country_code: string;
};

export type ConfirmOtpDto = {
  /**
   * Phone number of a user
   *
   * @example 9876543210
   */
  mobile_number: string;
  /**
   * Country code of a user
   *
   * @example +91
   */
  country_code: string;
  /**
   * @example 123456
   */
  otp: string;
  /**
   * @example 9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d
   */
  token: string;
};

export type ChangePasswordDto = {
  /**
   * Phone number of a user
   *
   * @example 9876543210
   */
  mobile_number: string;
  /**
   * Country code of a user
   *
   * @example +91
   */
  country_code: string;
  /**
   * @example Palm@2022
   */
  password: string;
  /**
   * @example Palm@2022
   */
  confirm_password: string;
};

export type RefreshTokenDto = {
  /**
   * @example 123456
   */
  refreshToken: string;
};

export type GroundSlotDto = {
  /**
   * Day of week: 0=Sunday … 6=Saturday
   *
   * @example 1
   */
  dayOfWeek: number;
  /**
   * Start time in HH:MM format
   *
   * @example 06:00
   */
  startTime: string;
  /**
   * End time in HH:MM format
   *
   * @example 10:00
   */
  endTime: string;
  /**
   * Price for this slot
   *
   * @example 500
   */
  price: number;
};

export type CreateGroundDto = {
  /**
   * Ground name
   *
   * @example PlayVerse Arena
   */
  name: string;
  /**
   * Ground description
   *
   * @example Best ground in the city
   */
  description?: string;
  /**
   * Street address
   *
   * @example 123 Main Street, Navrangpura
   */
  address?: string;
  /**
   * City
   *
   * @example Ahmedabad
   */
  city?: string;
  /**
   * Latitude
   *
   * @example 23.032
   */
  latitude?: number;
  /**
   * Longitude
   *
   * @example 72.521
   */
  longitude?: number;
  /**
   * Array of sport IDs supported by this ground
   *
   * @example 1
   * @example 2
   */
  sports: string[];
  /**
   * Working hour slots with pricing. Each slot maps a day/time range to a price.
   */
  slots: GroundSlotDto[];
  /**
   * Array of uploaded ground images (accepts plain string URLs or objects containing a url property)
   *
   * @example ground1.jpg
   * @example {"filename":"1785412662411.png","url":"/drive/files/1785412662411.png"}
   */
  images?: string[];
};

export type UpdateGroundSlotDto = {
  /**
   * Day of week: 0=Sunday … 6=Saturday
   *
   * @example 1
   */
  dayOfWeek?: number;
  /**
   * Start time in HH:MM format
   *
   * @example 06:00
   */
  startTime?: string;
  /**
   * End time in HH:MM format
   *
   * @example 10:00
   */
  endTime?: string;
  /**
   * Price for this slot
   *
   * @example 500
   */
  price?: number;
  /**
   * Slot status: 1=active, 0=inactive
   *
   * @example 1
   */
  status?: number;
};

export type UpdateGroundDto = {
  /**
   * Ground name
   *
   * @example PlayVerse Arena
   */
  name?: string;
  /**
   * Ground description
   */
  description?: string;
  /**
   * Street address
   */
  address?: string;
  /**
   * City
   *
   * @example Ahmedabad
   */
  city?: string;
  /**
   * Latitude
   *
   * @example 23.032
   */
  latitude?: number;
  /**
   * Longitude
   *
   * @example 72.521
   */
  longitude?: number;
  /**
   * Array of sport IDs
   *
   * @example 1
   * @example 2
   */
  sports?: string[];
  /**
   * Working hour slots with pricing. If provided, replaces all existing slots.
   */
  slots?: UpdateGroundSlotDto[];
  /**
   * Ground images. If provided, replaces all existing images (accepts plain string URLs or objects containing a url property).
   *
   * @example ground1.jpg
   * @example {"filename":"1785412662411.png","url":"/drive/files/1785412662411.png"}
   */
  images?: string[];
};

export type GroundImageDto = {
  /**
   * Uploaded filename
   *
   * @example 1785412662411.png
   */
  filename: string;
  /**
   * Uploaded file URL
   *
   * @example /drive/files/1785412662411.png
   */
  url: string;
};
