/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type ProfileImageDto = {
  /**
   * Uploaded filename
   *
   * @example 1785412662411.png
   */
  filename: string;
  /**
   * URL of the uploaded image
   *
   * @example /drive/files/1785412662411.png
   */
  url: string;
};

export type CreateUserDto = {
  /**
   * Display name of user
   *
   * @example Rajesh Kumar
   */
  display_name: string;
  /**
   * Country code of a user
   *
   * @example +91
   */
  country_code: string;
  /**
   * Phone number of a user
   *
   * @example 9876543210
   */
  mobile_number: string;
  /**
   * Role of the user
   *
   * @example PLAYER
   * @default PLAYER
   */
  role: "PLAYER" | "GROUND_OWNER" | "ORGANIZER" | "ADMIN";
  /**
   * Profile image upload object (filename and url), can also accept a plain URL string
   */
  profile_image?: ProfileImageDto;
  /**
   * Auth type of user. Local/Social media type
   *
   * @example Local
   */
  auth_type: string;
  /**
   * App type. App or Browser
   *
   * @example App
   */
  app_type: string;
  /**
   * Device os type
   *
   * @example Android
   */
  os: string;
  /**
   * Device brand name
   *
   * @example Samsung A50
   */
  brand: string;
  /**
   * Device model number
   *
   * @example SM-A12E
   */
  model_no: string;
  /**
   * Device serial number
   *
   * @example SA4545as45a4
   */
  serial_number: string;
  /**
   * version number
   *
   * @example 1.0
   */
  version_number: string;
  /**
   * FCM token of the device
   *
   * @example fcm_token_001
   */
  fcm_token?: string;
  /**
   * List of sport IDs that the user plays or is interested in
   *
   * @example 1
   * @example 2
   */
  sports?: string[];
  /**
   * Latitude coordinate of the user
   *
   * @example 23.0225
   */
  latitude?: number;
  /**
   * Longitude coordinate of the user
   *
   * @example 72.5714
   */
  longitude?: number;
};

export type LoginUserDto = {
  /**
   * Phone number of a user
   *
   * @example 9876543210
   */
  mobile_number: string;
  /**
   * Country code of a user
   *
   * @example +91
   */
  country_code: string;
  /**
   * Login type of user.
   *
   * @example App
   */
  app_type: string;
  /**
   * Device os type
   *
   * @example Android
   */
  os: string;
  /**
   * Device brand name
   *
   * @example Samsung A50
   */
  brand: string;
  /**
   * Device model number
   *
   * @example SM-A12E
   */
  model_no: string;
  /**
   * Device serial number
   *
   * @example SA4545as45a4
   */
  serial_number: string;
  /**
   * version number
   *
   * @example 1.0
   */
  version_number: string;
  /**
   * FCM token of the device
   *
   * @example fcm_token_001
   */
  fcm_token?: string;
  /**
   * Latitude coordinate of the user
   *
   * @example 23.0225
   */
  latitude?: number;
  /**
   * Longitude coordinate of the user
   *
   * @example 72.5714
   */
  longitude?: number;
};

export type ForgotPasswordDto = {
  /**
   * Phone number of a user
   *
   * @example 9876543210
   */
  mobile_number: string;
  /**
   * Country code of a user
   *
   * @example +91
   */
  country_code: string;
};

export type ConfirmOtpDto = {
  /**
   * Phone number of a user
   *
   * @example 9876543210
   */
  mobile_number: string;
  /**
   * Country code of a user
   *
   * @example +91
   */
  country_code: string;
  /**
   * @example 123456
   */
  otp: string;
  /**
   * @example 9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d
   */
  token: string;
  /**
   * FCM token of the device
   *
   * @example fcm_token_001
   */
  fcm_token?: string;
  /**
   * Device os type
   *
   * @example ANDROID
   */
  os?: string;
  /**
   * Device brand name
   *
   * @example Samsung A50
   */
  brand?: string;
  /**
   * Device model number
   *
   * @example SM-A12E
   */
  model_no?: string;
  /**
   * Device serial number
   *
   * @example SA4545as45a4
   */
  serial_number?: string;
  /**
   * version number
   *
   * @example 1.0
   */
  version_number?: string;
  /**
   * Latitude coordinate
   *
   * @example 23.0225
   */
  latitude?: number;
  /**
   * Longitude coordinate
   *
   * @example 72.5714
   */
  longitude?: number;
};

export type ChangePasswordDto = {
  /**
   * Phone number of a user
   *
   * @example 9876543210
   */
  mobile_number: string;
  /**
   * Country code of a user
   *
   * @example +91
   */
  country_code: string;
  /**
   * @example Palm@2022
   */
  password: string;
  /**
   * @example Palm@2022
   */
  confirm_password: string;
};

export type RefreshTokenDto = {
  /**
   * @example 123456
   */
  refreshToken: string;
};

export type PatchUserProfileDto = {
  /**
   * Display name of user
   *
   * @example Rajesh Kumar
   */
  display_name?: string;
  /**
   * Profile image upload object (filename and url), can also accept a plain URL string
   */
  profile_image?: ProfileImageDto;
  /**
   * List of sport IDs
   *
   * @example 1
   * @example 2
   */
  sports?: string[];
};

export type FindGameRequestDto = {
  /**
   * Natural language query representing player's intent
   *
   * @example I want to play badminton today around 7 PM. I'm intermediate and need one player.
   */
  prompt: string;
};

export type SendGameInviteDto = {
  /**
   * The ID of the match the user wants to join
   *
   * @example 38
   */
  matchId: number;
  /**
   * The ID of the ground slot
   *
   * @example 1001
   */
  slotId: number;
};

export type CreateBookingDto = {
  /**
   * Ground ID to book
   *
   * @example 1
   */
  groundId: number;
  /**
   * Slot ID to book
   *
   * @example 5
   */
  slotId: number;
  /**
   * Booking date (YYYY-MM-DD)
   *
   * @example 2026-08-20
   */
  bookingDate: string;
  /**
   * Sport ID (if ground supports multiple)
   *
   * @example 1
   */
  sportId?: number;
  /**
   * Optional notes for the booking
   */
  notes?: string;
};

export type CreateMatchDto = {
  /**
   * The ID of the sport
   *
   * @example 1
   */
  sportId: number;
  /**
   * Tournament ID, if applicable
   *
   * @example null
   */
  tournamentId?: number;
  /**
   * Ground ID, if applicable
   *
   * @example null
   */
  groundId?: number;
  /**
   * Home Team ID, if already created
   *
   * @example null
   */
  homeTeamId?: number;
  /**
   * Away Team ID, if already created
   *
   * @example null
   */
  awayTeamId?: number;
  /**
   * List of Home Team Player User IDs (1 for Singles, 2 for Doubles)
   *
   * @example 1
   */
  homePlayerIds: string[];
  /**
   * List of Away Team Player User IDs (1 for Singles, 2 for Doubles)
   *
   * @example 2
   */
  awayPlayerIds: string[];
  /**
   * Match type: SINGLES or DOUBLES
   *
   * @example SINGLES
   */
  matchType: string;
  /**
   * Scheduled time
   *
   * @example 2026-08-25T18:00:00Z
   */
  scheduledAt?: string;
  /**
   * Points required to win a game (default 11)
   *
   * @example 11
   */
  pointsPerGame?: number;
  /**
   * Whether team must win by 2 points (default true)
   *
   * @example true
   */
  winByTwo?: boolean;
  /**
   * Number of games/periods needed to win the match (default 2)
   *
   * @example 2
   */
  gamesToWin?: number;
};

export type GroundSlotDto = {
  /**
   * Day of week: 0=Sunday … 6=Saturday
   *
   * @example 1
   */
  dayOfWeek: number;
  /**
   * Start time in HH:MM format
   *
   * @example 06:00
   */
  startTime: string;
  /**
   * End time in HH:MM format
   *
   * @example 10:00
   */
  endTime: string;
  /**
   * Price for this slot
   *
   * @example 500
   */
  price: number;
};

export type CreateGroundDto = {
  /**
   * Ground name
   *
   * @example PlayVerse Arena
   */
  name: string;
  /**
   * Ground description
   *
   * @example Best ground in the city
   */
  description?: string;
  /**
   * Street address
   *
   * @example 123 Main Street, Navrangpura
   */
  address?: string;
  /**
   * City
   *
   * @example Ahmedabad
   */
  city?: string;
  /**
   * Latitude
   *
   * @example 23.032
   */
  latitude?: number;
  /**
   * Longitude
   *
   * @example 72.521
   */
  longitude?: number;
  /**
   * Array of sport IDs supported by this ground
   *
   * @example 1
   * @example 2
   */
  sports: string[];
  /**
   * Working hour slots with pricing. Each slot maps a day/time range to a price.
   */
  slots: GroundSlotDto[];
  /**
   * Array of uploaded ground images (accepts plain string URLs or objects containing a url property)
   *
   * @example ground1.jpg
   * @example {"filename":"1785412662411.png","url":"/drive/files/1785412662411.png"}
   */
  images?: string[];
};

export type UpdateGroundSlotDto = {
  /**
   * Day of week: 0=Sunday … 6=Saturday
   *
   * @example 1
   */
  dayOfWeek?: number;
  /**
   * Start time in HH:MM format
   *
   * @example 06:00
   */
  startTime?: string;
  /**
   * End time in HH:MM format
   *
   * @example 10:00
   */
  endTime?: string;
  /**
   * Price for this slot
   *
   * @example 500
   */
  price?: number;
  /**
   * Slot status: 1=active, 0=inactive
   *
   * @example 1
   */
  status?: number;
};

export type UpdateGroundDto = {
  /**
   * Ground name
   *
   * @example PlayVerse Arena
   */
  name?: string;
  /**
   * Ground description
   */
  description?: string;
  /**
   * Street address
   */
  address?: string;
  /**
   * City
   *
   * @example Ahmedabad
   */
  city?: string;
  /**
   * Latitude
   *
   * @example 23.032
   */
  latitude?: number;
  /**
   * Longitude
   *
   * @example 72.521
   */
  longitude?: number;
  /**
   * Array of sport IDs
   *
   * @example 1
   * @example 2
   */
  sports?: string[];
  /**
   * Working hour slots with pricing. If provided, replaces all existing slots.
   */
  slots?: UpdateGroundSlotDto[];
  /**
   * Ground images. If provided, replaces all existing images (accepts plain string URLs or objects containing a url property).
   *
   * @example ground1.jpg
   * @example {"filename":"1785412662411.png","url":"/drive/files/1785412662411.png"}
   */
  images?: string[];
};

export type GroundImageDto = {
  /**
   * Uploaded filename
   *
   * @example 1785412662411.png
   */
  filename: string;
  /**
   * Uploaded file URL
   *
   * @example /drive/files/1785412662411.png
   */
  url: string;
};

export type CreateTeamDto = {
  /**
   * @example 1
   */
  sportId: number;
  /**
   * @example Mumbai Mavericks
   */
  name: string;
  /**
   * @example MUM
   */
  shortName?: string;
  /**
   * @example https://example.com/logo.png
   */
  logo?: string;
  /**
   * @example Mumbai
   */
  city?: string;
  /**
   * @example We love to play!
   */
  description?: string;
};

export type TeamInvitationDto = {
  /**
   * @example 9876543210
   */
  phoneNumber: string;
};

export type ChallengeDto = {
  /**
   * @example 2
   */
  opponentTeamId: number;
  /**
   * @example 1
   */
  sportId: number;
  /**
   * @example 2026-08-25T10:00:00
   */
  scheduledAt: string;
};

export type CreateTournamentDto = {
  /**
   * ID of the sport (e.g. 5 for Pickleball)
   *
   * @example 5
   */
  sportId: number;
  /**
   * ID of the ground where tournament is held
   *
   * @example 1
   */
  ground_id?: number;
  /**
   * Name of the tournament
   *
   * @example PlayVerse Pickleball Open
   */
  name: string;
  /**
   * Format of the tournament
   *
   * @example KNOCKOUT
   */
  format: "KNOCKOUT" | "ROUND_ROBIN" | "GROUP_STAGE" | "GROUP_KNOCKOUT";
  /**
   * Start date of the tournament
   *
   * @example 2026-08-21T10:00:00.000Z
   */
  startDate?: string;
  /**
   * End date of the tournament
   *
   * @example 2026-08-28T18:00:00.000Z
   */
  endDate?: string;
  /**
   * Visibility of the tournament
   *
   * @example PUBLIC
   */
  visibility?: "PUBLIC" | "PRIVATE";
  /**
   * Maximum number of team participants allowed
   *
   * @example 16
   */
  maxTeams?: number;
  /**
   * Registration deadline datetime
   *
   * @example 2026-08-20T20:00:00.000Z
   */
  registrationDeadline?: string;
  /**
   * Points awarded for a win
   *
   * @example 3
   */
  pointsForWin?: number;
  /**
   * Points awarded for a draw
   *
   * @example 1
   */
  pointsForDraw?: number;
  /**
   * Points awarded for a loss
   *
   * @example 0
   */
  pointsForLoss?: number;
  /**
   * Estimated duration of a match in minutes
   *
   * @example 60
   */
  matchDurationMinutes?: number;
  /**
   * Registration type (INDIVIDUAL or TEAM)
   *
   * @example TEAM
   */
  registrationType?: "INDIVIDUAL" | "TEAM";
  /**
   * Maximum size of a team
   *
   * @example 5
   */
  teamSize?: number;
  /**
   * Minimum players required per team
   *
   * @example 1
   */
  minPlayersRequired?: number;
  /**
   * Whether captain approval is required to join a team
   *
   * @example false
   */
  teamApprovalRequired?: boolean;
  /**
   * Initial team name to register
   *
   * @example Thunder Warriors
   */
  initialTeamName?: string;
};

export type RegisterTeamDto = {
  /**
   * ID of the team registering
   *
   * @example 12
   */
  teamId: number;
};

export type SeedItem = {
  /**
   * Team ID
   *
   * @example 12
   */
  teamId: number;
  /**
   * Seed number (1-indexed)
   *
   * @example 1
   */
  seed: number;
};

export type ConfigureSeedingDto = {
  /**
   * List of team seeds mapping
   */
  seeds: SeedItem[];
};

export type GroupItem = {
  /**
   * Team ID
   *
   * @example 12
   */
  teamId: number;
  /**
   * Group Name (e.g. A, B, C)
   *
   * @example A
   */
  groupName: string;
};

export type ConfigureGroupsDto = {
  /**
   * List of team group mappings
   */
  groups: GroupItem[];
};

export type GenerateBracketsDto = {
  /**
   * Start date/time of the first match
   *
   * @example 2026-08-21T09:00:00.000Z
   */
  startDate: string;
  /**
   * Match duration in minutes
   *
   * @example 60
   */
  matchDurationMinutes?: number;
  /**
   * Ground ID where matches will be played
   *
   * @example 5
   */
  groundId: number;
  /**
   * Number of courts available at the ground
   *
   * @example 2
   */
  courtsAvailable?: number;
};
