/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
import * as reactQuery from "@tanstack/react-query";
import {
  type StackApiContext,
  useStackApiContext,
  queryKeyFn,
} from "./stackApiContext";
import { deepMerge } from "./stackApiUtils";
import type * as Fetcher from "./stackApiFetcher";
import { stackApiFetch } from "./stackApiFetcher";

type QueryFnOptions = {
  signal?: AbortController["signal"];
};

export type GetConfigError = Fetcher.ErrorWrapper<undefined>;

export type GetConfigVariables = StackApiContext["fetcherOptions"];

/**
 * Fetch dynamic configuration for onboarding (Goals and Conditions). Public endpoint.
 */
export const fetchGetConfig = (
  variables: GetConfigVariables,
  signal?: AbortSignal,
) =>
  stackApiFetch<undefined, GetConfigError, undefined, {}, {}, {}>({
    url: "/api/v1/mobile/config",
    method: "get",
    ...variables,
    signal,
  });

/**
 * Fetch dynamic configuration for onboarding (Goals and Conditions). Public endpoint.
 */
export function getConfigQuery(variables: GetConfigVariables): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<undefined>;
};

export function getConfigQuery(
  variables: GetConfigVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<undefined>)
    | reactQuery.SkipToken;
};

export function getConfigQuery(
  variables: GetConfigVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/api/v1/mobile/config",
      operationId: "getConfig",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) => fetchGetConfig(variables, signal),
  };
}

/**
 * Fetch dynamic configuration for onboarding (Goals and Conditions). Public endpoint.
 */
export const useSuspenseGetConfig = <TData = undefined,>(
  variables: GetConfigVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<undefined, GetConfigError, TData>,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useStackApiContext(options);
  return reactQuery.useSuspenseQuery<undefined, GetConfigError, TData>({
    ...getConfigQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Fetch dynamic configuration for onboarding (Goals and Conditions). Public endpoint.
 */
export const useGetConfig = <TData = undefined,>(
  variables: GetConfigVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<undefined, GetConfigError, TData>,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useStackApiContext(options);
  return reactQuery.useQuery<undefined, GetConfigError, TData>({
    ...getConfigQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type CompleteOnboardingError = Fetcher.ErrorWrapper<undefined>;

export type CompleteOnboardingVariables = {
  body?: Record<string, any>;
} & StackApiContext["fetcherOptions"];

/**
 * Complete user onboarding by saving health profile, goals, and conditions. Requires Supabase JWT.
 */
export const fetchCompleteOnboarding = (
  variables: CompleteOnboardingVariables,
  signal?: AbortSignal,
) =>
  stackApiFetch<
    undefined,
    CompleteOnboardingError,
    Record<string, any>,
    {},
    {},
    {}
  >({ url: "/api/v1/mobile/onboarding", method: "post", ...variables, signal });

/**
 * Complete user onboarding by saving health profile, goals, and conditions. Requires Supabase JWT.
 */
export const useCompleteOnboarding = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      CompleteOnboardingError,
      CompleteOnboardingVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useStackApiContext();
  return reactQuery.useMutation<
    undefined,
    CompleteOnboardingError,
    CompleteOnboardingVariables
  >({
    mutationFn: (variables: CompleteOnboardingVariables) =>
      fetchCompleteOnboarding(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type RegisterDeviceError = Fetcher.ErrorWrapper<undefined>;

export type RegisterDeviceVariables = {
  body?: Record<string, any>;
} & StackApiContext["fetcherOptions"];

/**
 * Register or update a device FCM token for push notifications.
 */
export const fetchRegisterDevice = (
  variables: RegisterDeviceVariables,
  signal?: AbortSignal,
) =>
  stackApiFetch<
    undefined,
    RegisterDeviceError,
    Record<string, any>,
    {},
    {},
    {}
  >({ url: "/api/v1/mobile/devices", method: "post", ...variables, signal });

/**
 * Register or update a device FCM token for push notifications.
 */
export const useRegisterDevice = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      RegisterDeviceError,
      RegisterDeviceVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useStackApiContext();
  return reactQuery.useMutation<
    undefined,
    RegisterDeviceError,
    RegisterDeviceVariables
  >({
    mutationFn: (variables: RegisterDeviceVariables) =>
      fetchRegisterDevice(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type UnregisterDeviceError = Fetcher.ErrorWrapper<undefined>;

export type UnregisterDeviceVariables = StackApiContext["fetcherOptions"];

/**
 * Unregister a device (e.g., on logout).
 */
export const fetchUnregisterDevice = (
  variables: UnregisterDeviceVariables,
  signal?: AbortSignal,
) =>
  stackApiFetch<undefined, UnregisterDeviceError, undefined, {}, {}, {}>({
    url: "/api/v1/mobile/devices/unique-hardware-id",
    method: "delete",
    ...variables,
    signal,
  });

/**
 * Unregister a device (e.g., on logout).
 */
export const useUnregisterDevice = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      UnregisterDeviceError,
      UnregisterDeviceVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useStackApiContext();
  return reactQuery.useMutation<
    undefined,
    UnregisterDeviceError,
    UnregisterDeviceVariables
  >({
    mutationFn: (variables: UnregisterDeviceVariables) =>
      fetchUnregisterDevice(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type CreateWidgetSessionError = Fetcher.ErrorWrapper<undefined>;

export type CreateWidgetSessionVariables = StackApiContext["fetcherOptions"];

/**
 * Get a Terra widget session URL to link a wearable device.
 */
export const fetchCreateWidgetSession = (
  variables: CreateWidgetSessionVariables,
  signal?: AbortSignal,
) =>
  stackApiFetch<undefined, CreateWidgetSessionError, undefined, {}, {}, {}>({
    url: "/api/v1/terra/widget-session",
    method: "post",
    ...variables,
    signal,
  });

/**
 * Get a Terra widget session URL to link a wearable device.
 */
export const useCreateWidgetSession = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      CreateWidgetSessionError,
      CreateWidgetSessionVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useStackApiContext();
  return reactQuery.useMutation<
    undefined,
    CreateWidgetSessionError,
    CreateWidgetSessionVariables
  >({
    mutationFn: (variables: CreateWidgetSessionVariables) =>
      fetchCreateWidgetSession(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type GetBiometricsQueryParams = {
  days?: number;
};

export type GetBiometricsError = Fetcher.ErrorWrapper<undefined>;

export type GetBiometricsVariables = {
  queryParams?: GetBiometricsQueryParams;
} & StackApiContext["fetcherOptions"];

/**
 * Fetch historical daily biometrics for the user.
 */
export const fetchGetBiometrics = (
  variables: GetBiometricsVariables,
  signal?: AbortSignal,
) =>
  stackApiFetch<
    undefined,
    GetBiometricsError,
    undefined,
    {},
    GetBiometricsQueryParams,
    {}
  >({ url: "/api/v1/terra/biometrics", method: "get", ...variables, signal });

/**
 * Fetch historical daily biometrics for the user.
 */
export function getBiometricsQuery(variables: GetBiometricsVariables): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<undefined>;
};

export function getBiometricsQuery(
  variables: GetBiometricsVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<undefined>)
    | reactQuery.SkipToken;
};

export function getBiometricsQuery(
  variables: GetBiometricsVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/api/v1/terra/biometrics",
      operationId: "getBiometrics",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) => fetchGetBiometrics(variables, signal),
  };
}

/**
 * Fetch historical daily biometrics for the user.
 */
export const useSuspenseGetBiometrics = <TData = undefined,>(
  variables: GetBiometricsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<undefined, GetBiometricsError, TData>,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useStackApiContext(options);
  return reactQuery.useSuspenseQuery<undefined, GetBiometricsError, TData>({
    ...getBiometricsQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Fetch historical daily biometrics for the user.
 */
export const useGetBiometrics = <TData = undefined,>(
  variables: GetBiometricsVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<undefined, GetBiometricsError, TData>,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useStackApiContext(options);
  return reactQuery.useQuery<undefined, GetBiometricsError, TData>({
    ...getBiometricsQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type TerraWebhookHeaders = {
  ["terra-signature"]?: string;
};

export type TerraWebhookError = Fetcher.ErrorWrapper<undefined>;

export type TerraWebhookVariables = {
  body?: Record<string, any>;
  headers?: TerraWebhookHeaders;
} & StackApiContext["fetcherOptions"];

/**
 * Handle webhooks from Terra. Verified via HMAC signature.
 */
export const fetchTerraWebhook = (
  variables: TerraWebhookVariables,
  signal?: AbortSignal,
) =>
  stackApiFetch<
    undefined,
    TerraWebhookError,
    Record<string, any>,
    TerraWebhookHeaders,
    {},
    {}
  >({ url: "/api/v1/terra/webhook", method: "post", ...variables, signal });

/**
 * Handle webhooks from Terra. Verified via HMAC signature.
 */
export const useTerraWebhook = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      TerraWebhookError,
      TerraWebhookVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useStackApiContext();
  return reactQuery.useMutation<
    undefined,
    TerraWebhookError,
    TerraWebhookVariables
  >({
    mutationFn: (variables: TerraWebhookVariables) =>
      fetchTerraWebhook(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type QueryOperation =
  | {
      path: "/api/v1/mobile/config";
      operationId: "getConfig";
      variables: GetConfigVariables | reactQuery.SkipToken;
    }
  | {
      path: "/api/v1/terra/biometrics";
      operationId: "getBiometrics";
      variables: GetBiometricsVariables | reactQuery.SkipToken;
    };
